import type { Quote, Broker } from '../types'

export const mockBroker: Broker = {
  id: 'broker-001',
  name: 'Alex Johnson',
  email: 'alex.johnson@smartquote.com',
  licenseNumber: 'LIC-2024-00123',
  agency: 'SmartQuote Insurance Group',
}

let quoteCounter = 1000

function generateRef(): string {
  return `SQ-${new Date().getFullYear()}-${String(++quoteCounter).padStart(6, '0')}`
}

export const mockQuotes: Quote[] = [
  {
    id: 'q-001',
    referenceNumber: 'SQ-2024-001001',
    type: 'car',
    status: 'approved',
    brokerId: 'broker-001',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    client: {
      firstName: 'Maria',
      lastName: 'Garcia',
      dateOfBirth: '1985-03-15',
      email: 'maria.garcia@email.com',
      phone: '5551234567',
      address: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
    },
    condition: {
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2021,
      vehicleVin: '4T1B11HK0KU234567',
      usage: 'personal',
      annualMileage: 12000,
      coverageLevel: 'standard',
      driverLicenseYears: 15,
      priorAccidents: 0,
    },
    result: {
      monthlyPremium: 142,
      annualPremium: 1704,
      deductible: 500,
      coverageLimit: 100000,
      effectiveDate: '2024-02-01',
      expiryDate: '2025-02-01',
      breakdown: { liability: 60, collision: 45, comprehensive: 25, medical: 12 },
    },
  },
  {
    id: 'q-002',
    referenceNumber: 'SQ-2024-001002',
    type: 'house',
    status: 'pending',
    brokerId: 'broker-001',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    client: {
      firstName: 'Robert',
      lastName: 'Chen',
      dateOfBirth: '1978-07-22',
      email: 'robert.chen@email.com',
      phone: '5559876543',
      address: '456 Oak Ave',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
    },
    condition: {
      propertyAddress: '456 Oak Ave',
      propertyCity: 'Seattle',
      propertyState: 'WA',
      propertyZip: '98101',
      yearBuilt: 1998,
      squareFootage: 2400,
      constructionType: 'wood',
      roofType: 'asphalt',
      roofAge: 8,
      occupancy: 'owner',
      hasSprinklers: false,
      hasSecuritySystem: true,
      hasPool: false,
      estimatedValue: 650000,
      desiredCoverage: 600000,
    },
  },
  {
    id: 'q-003',
    referenceNumber: 'SQ-2024-001003',
    type: 'health',
    status: 'approved',
    brokerId: 'broker-001',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    client: {
      firstName: 'Sarah',
      lastName: 'Williams',
      dateOfBirth: '1992-11-08',
      email: 'sarah.w@email.com',
      phone: '5554445555',
      address: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
    },
    condition: {
      planType: 'PPO',
      coverageType: 'individual',
      clientAge: 32,
      smokingStatus: 'never',
      bmi: 23.5,
      preExistingConditions: [],
      desiredDeductible: 1500,
      needsDental: true,
      needsVision: true,
      needsMental: false,
      prescriptionCount: 1,
    },
    result: {
      monthlyPremium: 387,
      annualPremium: 4644,
      deductible: 1500,
      coverageLimit: 5000000,
      effectiveDate: '2024-01-01',
      expiryDate: '2025-01-01',
      breakdown: { medical: 320, dental: 45, vision: 22 },
    },
  },
  {
    id: 'q-004',
    referenceNumber: 'SQ-2024-001004',
    type: 'car',
    status: 'rejected',
    brokerId: 'broker-001',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    client: {
      firstName: 'James',
      lastName: 'Miller',
      dateOfBirth: '1990-05-30',
      email: 'james.m@email.com',
      phone: '5556667777',
      address: '321 Elm St',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
    },
    condition: {
      vehicleMake: 'Ford',
      vehicleModel: 'Mustang',
      vehicleYear: 2022,
      vehicleVin: '1FA6P8CF9N5123456',
      usage: 'personal',
      annualMileage: 18000,
      coverageLevel: 'comprehensive',
      driverLicenseYears: 5,
      priorAccidents: 3,
    },
  },
]

export { generateRef }
