export const demoQuotes = [
  {
    referenceNumber: 'SQ-2024-001001',
    type: 'car',
    status: 'approved',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    client: {
      firstName: 'Maria',
      lastName: 'Garcia',
      dateOfBirth: '1985-03-15',
      email: 'maria.garcia@email.com',
      phone: '5551234567',
      address: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
    },
    condition: {
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2021,
      vehicleVin: '4T1B11HK0KU234567',
      usage: 'personal',
      annualMileage: 12000,
      coverageLevel: 'standard',
      driverLicenseYears: 15,
      priorAccidents: 0,
    },
  },
  {
    referenceNumber: 'SQ-2024-001002',
    type: 'house',
    status: 'pending',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    client: {
      firstName: 'Robert',
      lastName: 'Chen',
      dateOfBirth: '1978-07-22',
      email: 'robert.chen@email.com',
      phone: '5559876543',
      address: '456 Oak Ave',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
    },
    condition: {
      propertyAddress: '456 Oak Ave',
      propertyCity: 'Seattle',
      propertyState: 'WA',
      propertyZip: '98101',
      yearBuilt: 1998,
      squareFootage: 2400,
      constructionType: 'wood',
      roofType: 'asphalt',
      roofAge: 8,
      occupancy: 'owner',
      hasSprinklers: false,
      hasSecuritySystem: true,
      hasPool: false,
      estimatedValue: 650000,
      desiredCoverage: 600000,
    },
  },
  {
    referenceNumber: 'SQ-2024-001003',
    type: 'health',
    status: 'approved',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    client: {
      firstName: 'Sarah',
      lastName: 'Williams',
      dateOfBirth: '1992-11-08',
      email: 'sarah.w@email.com',
      phone: '5554445555',
      address: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
    },
    condition: {
      planType: 'PPO',
      coverageType: 'individual',
      clientAge: 32,
      smokingStatus: 'never',
      bmi: 23.5,
      preExistingConditions: [],
      desiredDeductible: 1500,
      needsDental: true,
      needsVision: true,
      needsMental: false,
      prescriptionCount: 1,
    },
  },
  {
    referenceNumber: 'SQ-2024-001004',
    type: 'car',
    status: 'rejected',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    client: {
      firstName: 'James',
      lastName: 'Miller',
      dateOfBirth: '1990-05-30',
      email: 'james.m@email.com',
      phone: '5556667777',
      address: '321 Elm St',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
    },
    condition: {
      vehicleMake: 'Ford',
      vehicleModel: 'Mustang',
      vehicleYear: 2022,
      vehicleVin: '1FA6P8CF9N5123456',
      usage: 'personal',
      annualMileage: 18000,
      coverageLevel: 'comprehensive',
      driverLicenseYears: 5,
      priorAccidents: 3,
    },
  },
]
